In [64]:
#1
import numpy as np

In [65]:
#2
mass = np.array([1, 2, 3])
mass_mass = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33]])

zero_mass = np.zeros(5)
ones_mass = np.ones(5)

two_mass = np.arange(2, 10, 2)

print("Обычный масив:", mass)
print("Матрица 3x3:\n", mass_mass)
print("Массив нулей:", zero_mass)
print("Массив едениц:", ones_mass)
print("Масив четных(2 - 10):", two_mass)

Обычный масив: [1 2 3]
Матрица 3x3:
 [[11 12 13]
 [21 22 23]
 [31 32 33]]
Массив нулей: [0. 0. 0. 0. 0.]
Массив едениц: [1. 1. 1. 1. 1.]
Масив четных(2 - 10): [2 4 6 8]


In [66]:
#3
print("Работа с mass_mass:\n")
print("Тип данных в масиве:", mass_mass.dtype)
print("Размерность масива:", mass_mass.shape)
print("Вложенность масива:", mass_mass.ndim)

Работа с mass_mass:

Тип данных в масиве: int64
Размерность масива: (3, 3)
Вложенность масива: 2


In [67]:
#4
print("Работа с mass_mass:\n")
print("Вывод всего масива:\n", mass_mass)
print("Вывод 2-3 строк:\n", mass_mass[1:3])
print("Вывод 1-2 столбцов из 1 строки:\n", mass_mass[0,0:2])
print("Вывод 3 столбца:\n", mass_mass[0:3,2:3])

Работа с mass_mass:

Вывод всего масива:
 [[11 12 13]
 [21 22 23]
 [31 32 33]]
Вывод 2-3 строк:
 [[21 22 23]
 [31 32 33]]
Вывод 1-2 столбцов из 1 строки:
 [11 12]
Вывод 3 столбца:
 [[13]
 [23]
 [33]]


In [68]:
#5
print("Работа с mass:\n")
print("Среднее значение в масиве:", mass.mean())
print("Максимальное значение:", mass.max())
print("Индекс максимального значения:",mass.argmax())
print("Минимальное значение:", mass.min())
print("Индекс синимального значения:",mass.argmin())

Работа с mass:

Среднее значение в масиве: 2.0
Максимальное значение: 3
Индекс максимального значения: 2
Минимальное значение: 1
Индекс синимального значения: 0
